const courseDB = [
    { "Study":"diploma", "categories": "", "programImg": 'img/CS.jpeg', "programName": "Computer Science", "campus": "KL, PG, JH", "totalFee": "RM17,800", "Career": "Junior Analyst Programmers, Junior Systems Analysts,Junior Software Engineers, Junior Systems Engineers, Junior Research Officers, Junior Quantitative Analysts, Junior Software Developers"},
    { "Study":"diploma", "categories": "", "programImg": 'img/IS.jpg', "programName": "Information Systems", "campus": "KL, PG, PK", "totalFee": "RM17,800", "Career": "Junior Programmers, Junior Systems Analysts, Junior SAP Support Consultants, Junior IT Support Executives, Junior IT Executives"},
    { "Study":"diploma", "categories": "", "programImg": 'img/IT.jpg', "programName": "Information Technology", "campus": "KL, PG, PK, JH, PH, SB", "totalFee": "RM17,800", "Career": "Junior Programmers, Junior Systems Analysts, Junior Network Support Officers, Junior IT Support Executives, Junior IT Executives, Web Developer"},
    { "Study":"diploma", "categories": "", "programImg": 'img/SE.jpg', "programName": "Software Engineering", "campus": "SB", "totalFee": "RM17,800", "Career": "Junior Software Engineers, Junior Software Developers, Junior Software Testers, Junior Web Developers, Junior Database Administrators, Junior Systems Analysts"} ,
    { "Study":"degree", "categories": "Science", "programImg": 'img/MMC.jpg', "programName": "Management Mathematics with Computing", "campus": "KL", "totalFee": "RM34,100", "Career": "Officers in financial institutions, Quantitative Analysts, Quality Managers, Research Officers, Research Officers, Financial Analysts, Management Consultants, Financial Planners and Advisors, Pricing Analysts, Market Risk Managers, Credit Risk Managers, Asset/Liability Managers, IT Managers, Programmers"},
    { "Study":"degree", "categories": "Computer Science", "programImg": 'img/IST.jpg', "programName": "Interactive Software Technology", "campus": "KL", "totalFee": "RM35,100", "Career": "Games Designers, Games Programmers, Games Software Engineers, Games Producers, Games Testers, Technical Lead, Web Designers, Multimedia Developers, Software Developers, Mobile Application Developers, Systems Analysts"},
    { "Study":"degree", "categories": "Computer Science", "programImg": 'img/DS.jpg', "programName": "Data Science", "campus": "KL, PG", "totalFee": "RM34,300", "Career": "Data Scientists, Data Engineers, Data Analyst, Data Modelling Engineers, Software Developers, Mobile Application Developers, Computer Science Researchers, Machine Learning Engineers"},
    { "Study":"degree", "categories": "Information Science", "programImg": 'img/EIS.jpg', "programName": "Interactive Software Technology", "campus": "KL", "totalFee": "RM34,300", "Career": "ERP Consultants, Business and Systems Analysts, Business Process Consultants, Business Intelligence Specialists, Data Warehouse Developers, IT Consultants, IT Managers, Programmers, Web Designers, Database Administrators"},
    { "Study":"degree", "categories": "Information Technology", "programImg": 'img/IS.jpg', "programName": "Information Security", "campus": "KL", "totalFee": "RM33,800", "Career": "Information Security Analysts, Information Security Consultants, Information Security Managers, Information Security Engineers, Information Security Administrators, Information Security Auditors, Forensics Analysts, Forensics Investigators, Security Software Developers, Mobile Application Developers, Network Security Engineers"},
    { "Study":"degree", "categories": "Information Technology", "programImg": 'img/IT.jpg', "programName": "Internet Technology", "campus": "KL, PG", "totalFee": "RM34,600", "Career": "Web Developers, Multimedia Developers, Mobile Application Developers, Systems Analysts, Network Engineers, IT Consultants, IT Managers, IoT Developers"},
    { "Study":"degree", "categories": "Information Technology", "programImg": 'img/SSD.jpg', "programName": "Software Systems Development", "campus": "KL, PG, PK, JH, PH, SB", "totalFee": "RM34,600", "Career": "Programmers, Web Developers, Multimedia Developers, Mobile Application Developers, Systems Analysts, Software Engineers, Database Administrators, Network Engineers, IT Consultants, IT Managers, IoT Developers"},
    { "Study":"degree", "categories": "Software Engineering", "programImg": 'img/SE.jpg', "programName": "Software Engineering", "campus": "KL, PG", "totalFee": "RM34,600" ,"Career": "Software Engineers, Software Testers, Software Quality Assurance Engineers, Software Developers, Software Architects, Systems Analysts, Web Developers, Mobile Application Developers, IT Consultants, IT and Project Managers, Programmers"}
]
